language: node_js

sudo: false

branches:
  only:
    - master

node_js:
  - 10
  - 11
  - 12
  - 13
  - lts/*
  - node

os:
  - windows
  - linux
  - osx
 
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules
  
before_install:
  - npm install -g npm
